<#
.SYNOPSIS
  Install rime-german-gloss into the Weasel (Rime for Windows) user directory.

.DESCRIPTION
  User directory detection order:
    1. -RimeUserDir parameter
    2. Registry HKCU:\Software\Rime\Weasel, value RimeUserDir (custom dir set in Weasel)
    3. %APPDATA%\Rime (Weasel default)

.PARAMETER RimeUserDir
  Explicit Rime user directory.
.PARAMETER Schema
  Schema IDs to enable the filter for, e.g. -Schema luna_pinyin,double_pinyin_flypy.
  Creates <id>.custom.yaml when absent; an existing file is never modified.
.PARAMETER Force
  Overwrite an existing, modified german_gloss\zh_de.tsv.
.PARAMETER Deploy
  Run WeaselDeployer.exe /deploy after installation.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File .\install-windows.ps1 -Schema luna_pinyin -Deploy
#>
[CmdletBinding()]
param(
  [string]$RimeUserDir,
  [string[]]$Schema = @(),
  [switch]$Force,
  [switch]$Deploy
)

$ErrorActionPreference = 'Stop'
$SrcDir = $PSScriptRoot
$FilterEntry = 'lua_filter@*german_gloss'
# 'powershell -File' passes 'a,b' as one string; accept comma-separated IDs.
$Schema = @($Schema | ForEach-Object { $_ -split ',' } | ForEach-Object { $_.Trim() } | Where-Object { $_ })

function Get-RegistryValue([string]$Path, [string]$Name) {
  try {
    $item = Get-ItemProperty -Path $Path -Name $Name -ErrorAction Stop
    return $item.$Name
  } catch {
    return $null
  }
}

if (-not $RimeUserDir) {
  $RimeUserDir = Get-RegistryValue 'HKCU:\Software\Rime\Weasel' 'RimeUserDir'
  if ($RimeUserDir) {
    Write-Host "User directory from registry (HKCU\Software\Rime\Weasel\RimeUserDir)."
  } else {
    $RimeUserDir = Join-Path $env:APPDATA 'Rime'
  }
}
$RimeUserDir = [Environment]::ExpandEnvironmentVariables($RimeUserDir)

if (-not (Test-Path -LiteralPath $RimeUserDir -PathType Container)) {
  throw "Rime user directory not found: $RimeUserDir. Deploy Weasel once, or pass -RimeUserDir."
}
Write-Host "==> $RimeUserDir"

$luaDir  = Join-Path $RimeUserDir 'lua'
$dictDir = Join-Path $RimeUserDir 'german_gloss'
New-Item -ItemType Directory -Force -Path $luaDir, $dictDir | Out-Null

Copy-Item -LiteralPath (Join-Path (Join-Path $SrcDir 'lua') 'german_gloss.lua') -Destination (Join-Path $luaDir 'german_gloss.lua') -Force
Write-Host '    installed lua\german_gloss.lua'

$dictSrc = Join-Path (Join-Path $SrcDir 'german_gloss') 'zh_de.tsv'
$dictDst = Join-Path $dictDir 'zh_de.tsv'
$modified = (Test-Path -LiteralPath $dictDst) -and
  ((Get-FileHash -LiteralPath $dictSrc).Hash -ne (Get-FileHash -LiteralPath $dictDst).Hash)
if ($modified -and -not $Force) {
  Copy-Item -LiteralPath $dictSrc -Destination "$dictDst.new" -Force
  Write-Host '    kept existing german_gloss\zh_de.tsv (modified); new copy at zh_de.tsv.new (use -Force to overwrite)'
} else {
  Copy-Item -LiteralPath $dictSrc -Destination $dictDst -Force
  Write-Host '    installed german_gloss\zh_de.tsv'
}

$baseSrc = Join-Path (Join-Path $SrcDir 'german_gloss') 'handedict.tsv'
if (Test-Path -LiteralPath $baseSrc) {
  Copy-Item -LiteralPath $baseSrc -Destination (Join-Path $dictDir 'handedict.tsv') -Force
  Write-Host '    installed german_gloss\handedict.tsv'
} else {
  Write-Host '    no german_gloss\handedict.tsv (run tools\build_handedict.py for the full dictionary)'
}

foreach ($id in $Schema) {
  $custom = Join-Path $RimeUserDir "$id.custom.yaml"
  if (-not (Test-Path -LiteralPath $custom)) {
    $text = "# generated by rime-german-gloss`npatch:`n  engine/filters/@next: $FilterEntry`n"
    [System.IO.File]::WriteAllText($custom, $text, (New-Object System.Text.UTF8Encoding $false))
    Write-Host "    created $id.custom.yaml"
  } elseif (Select-String -LiteralPath $custom -Pattern 'german_gloss' -SimpleMatch -Quiet) {
    Write-Host "    $id.custom.yaml already references german_gloss; unchanged"
  } else {
    Write-Host "    $id.custom.yaml exists and was NOT modified. Add under its 'patch:' key:"
    Write-Host "      engine/filters/@next: $FilterEntry"
  }
}

if ($Schema.Count -eq 0) {
  Write-Host ''
  Write-Host 'No -Schema given: the filter is installed but not enabled.'
  Write-Host 'Add to <schema_id>.custom.yaml in the user directory:'
  Write-Host '  patch:'
  Write-Host "    engine/filters/@next: $FilterEntry"
}

$deployer = $null
foreach ($key in 'HKLM:\SOFTWARE\Rime\Weasel', 'HKLM:\SOFTWARE\WOW6432Node\Rime\Weasel') {
  $root = Get-RegistryValue $key 'WeaselRoot'
  if ($root -and (Test-Path -LiteralPath (Join-Path $root 'WeaselDeployer.exe'))) {
    $deployer = Join-Path $root 'WeaselDeployer.exe'
    break
  }
}

Write-Host ''
if ($Deploy) {
  if (-not $deployer) {
    throw 'WeaselDeployer.exe not found via registry WeaselRoot; redeploy from the Weasel tray menu.'
  }
  Write-Host "Running $deployer /deploy"
  Start-Process -FilePath $deployer -ArgumentList '/deploy' -Wait
} else {
  Write-Host 'Now redeploy Rime: Weasel tray icon -> right click -> Deploy'
  if ($deployer) { Write-Host "  or run: & '$deployer' /deploy" }
}
