#!/usr/bin/env sh
# Install rime-german-gloss into Linux Rime user directories
# (fcitx5-rime, fcitx5-rime Flatpak, ibus-rime, fcitx-rime).
#
# Usage: ./install-linux.sh [--dir DIR]... [--schema ID]... [--force]
#   --dir DIR    install into DIR only (repeatable); default: every detected dir
#   --schema ID  enable the filter for schema ID by creating ID.custom.yaml
#                (repeatable), e.g. --schema luna_pinyin --schema double_pinyin_flypy
#   --force      overwrite an existing, modified german_gloss/zh_de.tsv
set -eu

SRC_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
FILTER_ENTRY='lua_filter@*german_gloss'

DIRS=""
SCHEMAS=""
FORCE=0

usage() { sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'; }

while [ $# -gt 0 ]; do
  case "$1" in
    --dir)    [ $# -ge 2 ] || { usage; exit 2; }; DIRS="$DIRS
$2"; shift 2 ;;
    --schema) [ $# -ge 2 ] || { usage; exit 2; }; SCHEMAS="$SCHEMAS $2"; shift 2 ;;
    --force)  FORCE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

if [ -z "$DIRS" ]; then
  data_home=${XDG_DATA_HOME:-$HOME/.local/share}
  config_home=${XDG_CONFIG_HOME:-$HOME/.config}
  for candidate in \
    "$data_home/fcitx5/rime" \
    "$HOME/.var/app/org.fcitx.Fcitx5/data/fcitx5/rime" \
    "$config_home/ibus/rime" \
    "$config_home/fcitx/rime"
  do
    if [ -d "$candidate" ]; then
      DIRS="$DIRS
$candidate"
    fi
  done
fi

DIRS=$(printf '%s\n' "$DIRS" | sed '/^$/d')
if [ -z "$DIRS" ]; then
  echo "No Rime user directory found. Checked:" >&2
  echo "  \${XDG_DATA_HOME:-~/.local/share}/fcitx5/rime" >&2
  echo "  ~/.var/app/org.fcitx.Fcitx5/data/fcitx5/rime" >&2
  echo "  \${XDG_CONFIG_HOME:-~/.config}/ibus/rime" >&2
  echo "  \${XDG_CONFIG_HOME:-~/.config}/fcitx/rime" >&2
  echo "Deploy Rime once, or pass --dir DIR." >&2
  exit 1
fi

install_into() {
  dir=$1
  echo "==> $dir"
  mkdir -p "$dir/lua" "$dir/german_gloss"
  cp "$SRC_DIR/lua/german_gloss.lua" "$dir/lua/german_gloss.lua"
  echo "    installed lua/german_gloss.lua"

  dict_src="$SRC_DIR/german_gloss/zh_de.tsv"
  dict_dst="$dir/german_gloss/zh_de.tsv"
  if [ -f "$dict_dst" ] && ! cmp -s "$dict_src" "$dict_dst" && [ "$FORCE" -ne 1 ]; then
    cp "$dict_src" "$dict_dst.new"
    echo "    kept existing german_gloss/zh_de.tsv (modified); new copy at zh_de.tsv.new (use --force to overwrite)"
  else
    cp "$dict_src" "$dict_dst"
    echo "    installed german_gloss/zh_de.tsv"
  fi

  for schema in $SCHEMAS; do
    custom="$dir/$schema.custom.yaml"
    if [ ! -e "$custom" ]; then
      {
        echo "# generated by rime-german-gloss"
        echo "patch:"
        echo "  engine/filters/@next: $FILTER_ENTRY"
      } > "$custom"
      echo "    created $schema.custom.yaml"
    elif grep -q 'german_gloss' "$custom"; then
      echo "    $schema.custom.yaml already references german_gloss; unchanged"
    else
      echo "    $schema.custom.yaml exists and was NOT modified. Add under its 'patch:' key:"
      echo "      engine/filters/@next: $FILTER_ENTRY"
    fi
  done
}

printf '%s\n' "$DIRS" | while IFS= read -r d; do
  install_into "$d"
done

if [ -z "$SCHEMAS" ]; then
  echo
  echo "No --schema given: the filter is installed but not enabled."
  echo "Add to <schema_id>.custom.yaml in the user directory:"
  echo "  patch:"
  echo "    engine/filters/@next: $FILTER_ENTRY"
fi

echo
echo "Now redeploy Rime:"
echo "  fcitx5-rime: tray menu -> Rime -> Deploy (重新部署)"
echo "  ibus-rime:   ibus menu -> Deploy (部署), or run: ibus restart"
