-- german_gloss.lua
-- librime-lua filter: append an offline German gloss to candidate comments.
--
-- Usage in a schema (or <schema>.custom.yaml patch):
--   engine/filters/@next: lua_filter@*german_gloss
--
-- Optional schema config (key = name space of the filter, default "german_gloss"):
--   german_gloss:
--     dictionary: german_gloss/zh_de.tsv   # relative to user/shared data dir, or absolute
--     base_dictionary: german_gloss/handedict.tsv  # optional big dictionary, "none" disables
--     opencc_config: t2s.json              # "none" disables script normalization
--     max_length: 60                       # characters shown per gloss, 0 = unlimited
--
-- `dictionary` holds the user's own entries and overrides `base_dictionary`,
-- which is generated by tools/build_handedict.py and silently skipped if absent.
--
-- Script normalization: dictionary keys and candidate texts are both mapped
-- to Simplified Chinese with OpenCC (default t2s.json, the same file librime's
-- simplifier uses), so one dictionary serves Traditional and Simplified output.
-- Exact matches take precedence over normalized ones. Keys of `base_dictionary`
-- are not normalized at load time; it is expected to list both scripts.
--
-- Dictionary format: UTF-8 TSV, one entry per line: <Chinese>\t<German>.
-- Empty lines and lines starting with '#' are ignored. Repeated keys are
-- joined with "; " in file order (exact duplicates are dropped).

local M = {}

local DEFAULT_DICT = "german_gloss/zh_de.tsv"
local DEFAULT_BASE_DICT = "german_gloss/handedict.tsv"
local DEFAULT_OPENCC = "t2s.json"
local DEFAULT_MAX_LENGTH = 60

-- Loaded dictionaries, shared by every session and schema of this Lua state.
local cache = {}

local function log_warn(msg)
  if log and log.warning then
    log.warning("[german_gloss] " .. msg)
  end
end

local function trim(s)
  if not s:find("^%s") and not s:find("%s$") then
    return s -- common case, keeps loading a large dictionary fast
  end
  return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

-- Parse TSV content from an open file handle into a table text -> gloss.
function M.parse(fh)
  local dict = {}
  local first = true
  for raw in fh:lines() do
    local line = raw -- loop variables are read-only in Lua 5.5
    if first then
      line = line:gsub("^\239\187\191", "") -- strip UTF-8 BOM
      first = false
    end
    if line:byte(-1) == 13 then
      line = line:sub(1, -2)                -- tolerate CRLF files
    end
    if line ~= "" and line:sub(1, 1) ~= "#" then
      local key, gloss = line:match("^([^\t]+)\t(.+)$")
      if key then
        key, gloss = trim(key), trim(gloss)
        if key ~= "" and gloss ~= "" then
          local old = dict[key]
          if old == nil then
            dict[key] = gloss
          elseif old ~= gloss
              and ("; " .. old .. "; "):find("; " .. gloss .. "; ", 1, true) == nil then
            dict[key] = old .. "; " .. gloss
          end
        end
      end
    end
  end
  return dict
end

local function is_absolute(path)
  return path:sub(1, 1) == "/" or path:match("^%a:[/\\]") ~= nil
      or path:sub(1, 2) == "\\\\"
end

local function resolve_path(rel)
  if is_absolute(rel) then
    return { rel }
  end
  local paths = {}
  if rime_api then
    if rime_api.get_user_data_dir then
      paths[#paths + 1] = rime_api.get_user_data_dir() .. "/" .. rel
    end
    if rime_api.get_shared_data_dir then
      paths[#paths + 1] = rime_api.get_shared_data_dir() .. "/" .. rel
    end
  end
  return paths
end

-- Load dictionary `rel`; `optional` suppresses the warning when it is absent.
function M.load(rel, optional)
  for _, path in ipairs(resolve_path(rel)) do
    local fh = io.open(path, "r")
    if fh then
      local dict = M.parse(fh)
      fh:close()
      return dict, path
    end
  end
  if not optional then
    log_warn("dictionary not found: " .. rel)
  end
  return {}, nil
end

-- Forget cached dictionaries (they are otherwise kept until Rime is redeployed).
function M.clear_cache()
  cache = {}
end

-- Shorten `text` to at most `max` UTF-8 characters, marking the cut with "…".
function M.truncate(text, max)
  if max == nil or max <= 0 or #text <= max then
    return text
  end
  local count = 0
  for pos in text:gmatch("()[^\128-\191]") do
    count = count + 1
    if count > max then
      return (text:sub(1, pos - 1):gsub("[%s;,]+$", "")) .. "…"
    end
  end
  return text
end

-- Return the comment to show for a candidate with comment `old` and gloss `gloss`.
function M.merge_comment(old, gloss)
  if old == nil or old == "" then
    return " " .. gloss
  end
  return old .. " " .. gloss
end

-- Return a candidate carrying the merged comment. Setting cand.comment is a
-- silent no-op in librime-lua for Shadow/Uniquified candidates (e.g. produced
-- by simplifier or uniquifier), so fall back to wrapping in a ShadowCandidate.
function M.annotate(cand, gloss)
  local comment = M.merge_comment(cand.comment, gloss)
  cand.comment = comment
  if cand.comment == comment then
    return cand
  end
  return ShadowCandidate(cand, cand.type, cand.text, comment)
end

-- Return an OpenCC converter for `name`, or nil if unavailable
-- (librime-lua without Opencc support, or config file not found).
function M.make_converter(name)
  if name == nil or name == "" or name == "none" or Opencc == nil then
    return nil
  end
  local ok, conv = pcall(Opencc, name)
  if ok and conv then
    return conv
  end
  log_warn("OpenCC config unavailable, script normalization disabled: " .. name)
  return nil
end

-- Add normalized aliases for keys whose normalized form is not yet present.
function M.add_aliases(dict, conv)
  local aliases = {}
  for key, gloss in pairs(dict) do
    local norm = conv:convert(key)
    if norm ~= key and dict[norm] == nil and aliases[norm] == nil then
      aliases[norm] = gloss
    end
  end
  for key, gloss in pairs(aliases) do
    dict[key] = gloss
  end
end

-- Exact match first, then match on the normalized text.
function M.lookup(dict, conv, text)
  local gloss = dict[text]
  if gloss == nil and conv ~= nil then
    local norm = conv:convert(text)
    if norm ~= text then
      gloss = dict[norm]
    end
  end
  return gloss
end

function M.init(env)
  local ns = (env.name_space or ""):gsub("^%*", "")
  if ns == "" then ns = "german_gloss" end
  local rel = DEFAULT_DICT
  local base_rel = DEFAULT_BASE_DICT
  local opencc_config = DEFAULT_OPENCC
  env.gloss_max_length = DEFAULT_MAX_LENGTH
  local config = env.engine and env.engine.schema and env.engine.schema.config
  if config then
    local v = config:get_string(ns .. "/dictionary")
    if v and v ~= "" then rel = v end
    local b = config:get_string(ns .. "/base_dictionary")
    if b and b ~= "" then base_rel = b end
    local o = config:get_string(ns .. "/opencc_config")
    if o then opencc_config = o end
    local m = tonumber(config:get_string(ns .. "/max_length"))
    if m then env.gloss_max_length = m end
  end

  local key = rel .. "\n" .. base_rel .. "\n" .. opencc_config
  local entry = cache[key]
  if entry == nil then
    entry = { dict = M.load(rel), base = {} }
    if base_rel ~= "none" then
      entry.base = M.load(base_rel, true)
    end
    entry.conv = M.make_converter(opencc_config)
    if entry.conv then
      M.add_aliases(entry.dict, entry.conv)
    end
    cache[key] = entry
  end
  env.gloss_dict = entry.dict
  env.gloss_base = entry.base
  env.gloss_conv = entry.conv
end

function M.func(input, env)
  local dict = env.gloss_dict or {}
  local conv = env.gloss_conv
  local base = env.gloss_base or {}
  local max_length = env.gloss_max_length
  for cand in input:iter() do
    -- A failing lookup must never cost the user a candidate.
    local ok, annotated = pcall(function()
      local gloss = M.lookup(dict, conv, cand.text) or M.lookup(base, conv, cand.text)
      return gloss and M.annotate(cand, M.truncate(gloss, max_length))
    end)
    yield(ok and annotated or cand)
  end
end

function M.fini(env)
  env.gloss_dict = nil
  env.gloss_base = nil
  env.gloss_conv = nil
end

return M
