#!/usr/bin/env python3
"""Build german_gloss/handedict.tsv from HanDeDict (CC BY-SA 2.0).

Usage: tools/build_handedict.py [--source FILE] [--output FILE]
  --source FILE  local handedict.u8 (CEDICT format); default: download from GitHub
  --output FILE  default: german_gloss/handedict.tsv next to this repository's lua/

Every entry is written under its Traditional and its Simplified headword, so the
filter needs no OpenCC conversion for this dictionary. Standard library only.
"""
import argparse
import os
import re
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/gugray/HanDeDict/master/handedict.u8"
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENTRY = re.compile(r"^(\S+) (\S+) \[[^\]]*\] /(.*)/\s*$")
EXAMPLES = re.compile(r";?\s*Bsp\.:.*$")
UNVERIFIED = re.compile(r"\s*\(u\.E\.\)")
PROPER_NAME = re.compile(r"\((?:[^)]*,\s*)?(?:Eig|Fam|Pers|Geo)\b")


def clean(sense):
    sense = EXAMPLES.sub("", sense)
    sense = UNVERIFIED.sub("", sense)
    return " ".join(sense.split()).strip(" ;,")


def parse(lines):
    """Yield (traditional, simplified, [senses]) per dictionary entry."""
    for line in lines:
        if line.startswith("#"):
            continue
        m = ENTRY.match(line.lstrip("﻿"))
        if not m:
            continue
        senses = [s for s in (clean(p) for p in m.group(3).split("/")) if s]
        if senses:
            yield m.group(1), m.group(2), senses


def build(lines):
    """Return {headword: [senses]}; a headword's own Traditional entries come
    before entries that merely simplify to it, proper names come last."""
    own, borrowed = {}, {}
    for trad, simp, senses in parse(lines):
        own.setdefault(trad, []).extend(senses)
        if simp != trad:
            borrowed.setdefault(simp, []).extend(senses)
    result = {}
    for key in own.keys() | borrowed.keys():
        senses = list(dict.fromkeys(own.get(key, []) + borrowed.get(key, [])))
        senses.sort(key=lambda s: PROPER_NAME.search(s) is not None)
        result[key] = senses
    return result


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source")
    ap.add_argument("--output", default=os.path.join(REPO, "german_gloss", "handedict.tsv"))
    args = ap.parse_args()

    if args.source:
        with open(args.source, encoding="utf-8") as fh:
            text = fh.read()
    else:
        print("downloading " + URL, file=sys.stderr)
        with urllib.request.urlopen(URL) as resp:
            text = resp.read().decode("utf-8")

    entries = build(text.splitlines())
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w", encoding="utf-8", newline="\n") as out:
        out.write("# Generated by tools/build_handedict.py from HanDeDict\n")
        out.write("# https://handedict.zydeo.net/ - licensed CC BY-SA 2.0\n")
        for key in sorted(entries):
            if "\t" in key or key.startswith("#"):
                continue
            out.write(key + "\t" + "; ".join(entries[key]) + "\n")
    print("wrote %d headwords to %s" % (len(entries), args.output), file=sys.stderr)


if __name__ == "__main__":
    main()
